//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleGeolocationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_DailySalesTask
    {
        public long DailySalesTaskID { get; set; }
        public Nullable<long> UserID { get; set; }
        public string BuyerName { get; set; }
        public string Description { get; set; }
        public string Achivement { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
